version: 1.0.{build}
install:
  - cmd: git submodule update --init --recursive
build:
  project: src/STACK.sln
  verbosity: minimal
test:
  categories:
    except:
    - GPU
    - FileSystem
skip_commits:
  files:
    - **/*.png
    - **/*.gif
    - **/*.md        