version: 1.0.{build}
image: Visual Studio 2019
install:  
  - echo installing
  - git submodule update --init --recursive
build:
  project: src/STACK.sln
  verbosity: detailed
test:
  categories:
    except:
    - GPU
    - FileSystem
skip_commits:
  files:
    - '**/*.png'
    - '**/*.gif'
    - '**/*.md'     