  
REM ------------------------------------------------------------------------------
REM  <auto-generated>
REM      This code was generated by a tool on 28.01.2018 14:19:44.
REM 
REM      Changes to this file may cause incorrect behavior and will be lost if
REM      the code is regenerated.
REM  </auto-generated>
REM ------------------------------------------------------------------------------

fxc.exe /T fx_2_0 "shaders\BloomCombine.fx" /Fo"bin\shaders\BloomCombine.fxb"
fxc.exe /T fx_2_0 "shaders\BloomExtract.fx" /Fo"bin\shaders\BloomExtract.fxb"
fxc.exe /T fx_2_0 "shaders\GaussianBlur.fx" /Fo"bin\shaders\GaussianBlur.fxb"
fxc.exe /T fx_2_0 "shaders\Normalmap.fx" /Fo"bin\shaders\Normalmap.fxb"
ContentCompiler.exe stacklogo.png bin\stacklogo TextureImporter TextureProcessor true
ContentCompiler.exe fonts\stack.spritefont bin\fonts\stack FontDescriptionImporter FontDescriptionProcessor true
