  
// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool on 18.11.2023 22:23:54.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace STACK
{
    public static partial class content
    {
        public const string stacklogo = "stacklogo";

        public static partial class fonts
        {
            public const string _path_ = "fonts/";
            public const string stack = "fonts/stack";
        }

        public static partial class shaders
        {
            public const string _path_ = "shaders/";
            public const string BloomCombine = "shaders/BloomCombine";
            public const string BloomExtract = "shaders/BloomExtract";
            public const string GaussianBlur = "shaders/GaussianBlur";
            public const string Normalmap = "shaders/Normalmap";
        }

        public static partial class Skins
        {
            public const string _path_ = "Skins/";
            public const string Default = "Skins/Default";
        }
    }
}
