  
// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by a tool on 28.01.2018 14:19:47.
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace STACK
{
    public static partial class content
    {
        public static string stacklogo = "stacklogo";

        public static partial class fonts
        {
            public static string _path_ = "fonts\\";
            public static string stack = "fonts\\stack";
        }

        public static partial class shaders
        {
            public static string _path_ = "shaders\\";
            public static string BloomCombine = "shaders\\BloomCombine";
            public static string BloomExtract = "shaders\\BloomExtract";
            public static string GaussianBlur = "shaders\\GaussianBlur";
            public static string Normalmap = "shaders\\Normalmap";
        }
    }
}
